### ISSUE TITLE
Discussion over current setup for Experiment Factory and Mturk

### ISSUE THREAD

**Issue by IanEisenberg** [expfactory/expfactory-docker#66] opened 2016-03-13 02:12 UTC
Referencing @poldrack, @bissettp, and @zenkavi, along with @vsoch for this discussion.

@vosch recently updated the experiment factory structure quite a bit. Now clicking on "start experiment" at the end of consent/instructions in the Mturk iframe will open a new page which will either say "You have to be in this experiment to proceed", "We have no more experiments for you at this time" or it shows you the next experiment. You can do multiple experiments in a row, but if you leave and want to start again, you go to the Mturk page again, go through consent/instructions, click "start experiment" and go.

Because this is a fundamental way we deploy experiments I thought it'd be good to have everyone get an update. I think some choices @vsoch made are great beyond our current plans. 

**(1)** Each time a person returns they are shown ad/consent/instructions again. While potentially annoying to workers, I like that people are reminded about "what's going on" before each "session" of experiments. It does mean that people who do the session in more batches will see instructions/consent more often. Is that an inadvertent manipulation we'd like to avoid? I think the benefits of reminding people each session are good, and none of the instructions mention anything about our DVs (e.g. "we are looking at self regulation").

**(2)** At the end of the tasks the HIT is not returned. This means that every person's HIT is returned at expiration regardless of when they actually complete the HIT. This has some Pros and Cons. 

**Cons:** a little weird - turkers are used to having their HIT returned at completion of work. Their pay will be delayed, etc. They may see that they still have an outstanding HIT, try to continue, and come back to "no more experiments" and get annoyed, and give us bad reviews.

 **Pros** (and here I think there is potential in the future), this setup allows us to _phase_ deployment. Basically we can give a set of people a battery with 12 tasks in it, wait until they complete all of them, and then add more tasks. The HIT is still alive so we just need some way to let them know to check it again. Not sure when we'd use this, but considering that right now the infrastructure is built to randomly deploy experiments it may be a useful workaround to control order (though maybe we want another way to control presentation order in the future), or create a forced delay between tasks. Additionally I imagine this approach is simpler, which will be helpful (especially when @vosch doesn't have as much time to maintain this infrastructure!)

**Comment by poldrack** [comment] 2016-03-13 02:16
I would not be worried about the differences in instruction time.  seems like the benefits outweigh any possible problems
I don’t have strong feelings about #2

> On Mar 12, 2016, at 6:12 PM, IanEisenberg <notifications@github.com> wrote:
> 
> Referencing @poldrack <https://github.com/poldrack>, @bissettp <https://github.com/bissettp>, and @zenkavi <https://github.com/zenkavi>, along with @vsoch <https://github.com/vsoch> for this discussion.
> 
> @vosch <https://github.com/vosch> recently updated the experiment factory structure quite a bit. Now clicking on "start experiment" at the end of consent/instructions in the Mturk iframe will open a new page which will either say "You have to be in this experiment to proceed", "We have no more experiments for you at this time" or it shows you the next experiment. You can do multiple experiments in a row, but if you leave and want to start again, you go to the Mturk page again, go through consent/instructions, click "start experiment" and go.
> 
> Because this is a fundamental way we deploy experiments I thought it'd be good to have everyone get an update. I think some choices @vsoch <https://github.com/vsoch> made are great beyond our current plans.
> 
> (1) Each time a person returns they are shown ad/consent/instructions again. While potentially annoying to workers, I like that people are reminded about "what's going on" before each "session" of experiments. It does mean that people who do the session in more batches will see instructions/consent more often. Is that an inadvertent manipulation we'd like to avoid? I think the benefits of reminding people each session are good, and none of the instructions mention anything about our DVs (e.g. "we are looking at self regulation").
> 
> (2) At the end of the tasks the HIT is not returned. This means that every person's HIT is returned at expiration regardless of when they actually complete the HIT. This has some Pros and Cons.
> 
> Cons: a little weird - turkers are used to having their HIT returned at completion of work. Their pay will be delayed, etc. They may see that they still have an outstanding HIT, try to continue, and come back to "no more experiments" and get annoyed, and give us bad reviews.
> 
> Pros (and here I think there is potential in the future), this setup allows us to phase deployment. Basically we can give a set of people a battery with 12 tasks in it, wait until they complete all of them, and then add more tasks. The HIT is still alive so we just need some way to let them know to check it again. Not sure when we'd use this, but considering that right now the infrastructure is built to randomly deploy experiments it may be a useful workaround to control order (though maybe we want another way to control presentation order in the future), or create a forced delay between tasks. Additionally I imagine this approach is simpler, which will be helpful (especially when @vosch <https://github.com/vosch> doesn't have as much time to maintain this infrastructure!)
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/expfactory/expfactory-docker/issues/66>.
> 

—
Russell A. Poldrack
Professor of Psychology
Bldg. 420, Jordan Hall
Stanford University
Stanford, CA 94305

poldrack@stanford.edu
http://www.poldracklab.org/

**Comment by vsoch** [comment] 2016-03-13 02:43
For 1) This actually isn't the case (although it's unavoidable with a preview!). Refreshing the page with the serve URL given that the worker_id and assignment_id are defined in the URL should go to the next experiment sans the instructions, because it's always [this view](https://github.com/expfactory/expfactory-docker/blob/master/expdj/apps/turk/views.py#L59). Again, this would need to be tested with real MTurk deployment, because it's not possible with a preview, or just add the needed variables to the URL. If someone wants to test this, it would be greatly helpful!

For 2) What do you mean the HIT isn't "returned" ? I don't think I understand this lingo :) When all experiments are complete [when a user finishes](https://github.com/expfactory/expfactory-docker/blob/master/expdj/apps/turk/views.py#L343), the HIT goes through processing to be approved  OR when the total time to complete the battery runs out, the same thing happens (a task [is generated](https://github.com/expfactory/expfactory-docker/blob/master/expdj/apps/turk/views.py#L96) when the hit is served if it is newly created) In either case, this [task is called](https://github.com/expfactory/expfactory-docker/blob/master/expdj/apps/turk/tasks.py#L16) run via celery/redis.

I think you referenced an actual user named vosoch a few times - likely the much more trendy, in "vo"gue version of me :)

**Comment by vsoch** [comment] 2016-03-13 02:51
I think it would be worth telling the Turkers in the instructions to keep the URL handy - if they go back to it in the Amazon window it's going to show them the url that ends with /serve again, and if they just go to the /accept URL it won't show the intro stuffs.

**Comment by IanEisenberg** [comment] 2016-03-13 03:25
For (2) I'm definitely misusing lingo! By "return HIT" I mean, submit HIT - as in send the HIT to amazon says "this was done! pay the good worker!". I was basing this on the fact that I just completed a battery on sandbox, but the HIT is still "available" to me. Wouldn't it go away otherwise?

For (1) I'm not using a preview. After I accepted a HIT if I click "continue working on this HIT" it brings me back to the iFrame which has the ad/consent/experiment again (just like when I start). Like you said, they can just use the url if you want to skip. I personally like the repeated ad/consent/instructions, so I'm fine with it as is.

**Comment by vsoch** [comment] 2016-03-13 03:31
Hmm, definitely not desired behavior. It's hard to tell what is limited to sandbox vs. bug. I will test this tomorrow.

**Comment by vsoch** [comment] 2016-03-13 07:56
ok - I just found the worker Sandbox (didn't see this before, the aws UI is really hard to navigate!). Here is how the HIT looks in the window before I've accepted it:

![image](https://cloud.githubusercontent.com/assets/814322/13727504/b1c7cc0e-e8a9-11e5-989e-9d6c4c46c699.png)

Note that the embedded URL is for the instructions view, with ASSIGNMENT_ID_NOT_ASSIGNED to indicate that I have not accepted:

![image](https://cloud.githubusercontent.com/assets/814322/13727511/1e7ec3ca-e8aa-11e5-8603-d3ba6b382b37.png)


Note how this URL looks:

      https://expfactory.org/turk/7?assignmentId=ASSIGNMENT_ID_NOT_AVAILABLE&hitId=3S4TINXCC089U75TSLX22I4E4FTBOM

The "turk" at the beginning means that I have not accepted, along with ASSIGNMENT_ID_NOT_AVAILABLE. The first part will take me to the instructions page automaticallt. The second part determines the rendering of the link_url in the page to be this:

![image](https://cloud.githubusercontent.com/assets/814322/13727515/49a870a0-e8aa-11e5-97d3-672aa6bd6f2d.png)

However, now I can click the "Accept HIT" button:

![image](https://cloud.githubusercontent.com/assets/814322/13727519/5ff4618e-e8aa-11e5-8bb3-e4ae4785bdb0.png)

Confirmed that accepting opens in a new window! The URL now looks like this:

https://expfactory.org/accept/5/?assignmentId=3QY5DC2MXS6X6DZZJB089YJ54R8FUA&amp;workerId=A3E3J85MUM8YKG&amp;turkSubmitTo=https://workersandbox.mturk.com&amp;hitId=3SU800BH86DRBIRF7P61WDR28XLQUL

Note the "accept" at the beginning. This is the correct URL for serving the HIT. The page looks as before:

![image](https://cloud.githubusercontent.com/assets/814322/13727527/8f86400c-e8aa-11e5-815f-8c5d3c0a08ed.png)

except now the "Start Expermient" button will open the actual experiment in a new window instead of the page shown previously:

![image](https://cloud.githubusercontent.com/assets/814322/13727530/bfaf1984-e8aa-11e5-8cf3-41092489dd08.png)

This is the URL that we would instruct the worker to keep. Without doing anything, I tried refreshing this page, and confirmed that it doesn't go back to the instructions. I tried this at the beginning, in the middle of, and at the end and got this same behavior. Here I finish the "Angling Fish Task"

![image](https://cloud.githubusercontent.com/assets/814322/13727550/7a06e6b8-e8ab-11e5-8035-e709f2aab1ba.png)

If I finish the experiment I see this:

![image](https://cloud.githubusercontent.com/assets/814322/13727456/25dc9e46-e8a8-11e5-8cbe-3f82f86111e1.png)

and click "Redo" I am again taken to the start, and if I click "Next Experiment" I then finish and am told there are no more in the battery (my battery has N=1 experiments):

![image](https://cloud.githubusercontent.com/assets/814322/13727467/94a49de2-e8a8-11e5-8bdd-0d224365d843.png)

I then went back to the original window, and I have the option to return the HIT. If you look at the previous screen shot, I had this option before as well - the Turker always has the option to "give up" the HIT:

![image](https://cloud.githubusercontent.com/assets/814322/13727553/99ab2100-e8ab-11e5-9974-5670484ae133.png)

 I don't have the option to do it again, even in sandbox:

![image](https://cloud.githubusercontent.com/assets/814322/13727561/d10e66c0-e8ab-11e5-82ca-e4f814d56ea5.png)


![image](https://cloud.githubusercontent.com/assets/814322/13727486/0a743eba-e8a9-11e5-9559-9044de7913d4.png)

in the Requester window, the HIT is still shown to exist, with assignments remaining, I don't see any indication that I've (as a worker) have completed the HIT:

![image](https://cloud.githubusercontent.com/assets/814322/13727573/578db5ca-e8ac-11e5-8bf3-fe7f803f78ed.png)

I first had a hunch that the "automatically approve" time was too long, and did the experiment again with a new HIT. This wasn't the case - it didn't change the view above. I realized that the information about the assignments didn't appear to be showing up here. Then I saw the workers Tab. This is where the record is kept!

![image](https://cloud.githubusercontent.com/assets/814322/13727589/261e70f0-e8ad-11e5-9a95-65627059f14a.png)

There is the ID for my worker that just finished the HIT, and I can see 100% approval rate:

![image](https://cloud.githubusercontent.com/assets/814322/13727594/58a26202-e8ad-11e5-9a17-7b6b0776da78.png)

My experience of the current functionality is reported above, and (at least for sandbox) things seem to be working fairly as expected. @IanEisenberg I am not able to reproduce the following behavior you reported:

- not being able to return the HIT at the end of the task
- returning to the iframe with ad / instructions after accept --> Start Experiment

if you could provide a detailed walk through and show your concerns it would provide useful material for debugging. Thanks!

**Comment by vsoch** [comment] 2016-03-13 08:13
More subtle concerns that I have:

- We currently don't do any "double" checks for worker validation - when the worker comes in with an assignment ID and worker ID, we create the entry in our database without asking questions. If there were somehow a blip where the worker accidentally modified the URL for either of these IDs, we would still create the database entry, and not catch this until further down the line when an assignment ID / worker ID was sent to AWS to calculate reward, etc, and not found. This is pretty unlikely and probably ok as is for the pilot, but a concern and bug for deployment beyond that, and should be fixed.
- We currently don't have any kind of dashboard (on our end) that can show current active / finished, workers. Again, this is not essential for the pilot, but would be useful / needed for down the road, especially given some kind of manual checking to allocate credit or reward.
- THe steps reported from my first post need to be tested outside of sandbox, in "real" MTurk to ensure that the assignment count does go down as expected, and a reward (!=0) is granted automatically to the Turker upon completion of the task. We also need to test generating a worker that doesn't finish the task, and seeing if the celery job triggers if the worker doesn't return it. These are the kinds of things I had in mind when I mentioned testing MTurk, along with basic reporting as I've done above.

**Comment by zenkavi** [comment] 2016-03-13 08:19
I'm not sure if I have followed the discussion completely. What then are the major changes that you have made @vsoch that @IanEisenberg tried laying out?

Some additional questions that aren't very organized: 
Right now subjects are asked to come back by storing a URL and coming back to it outside of MTurk (which I think could be problematic - what if they forget, loose etc.)
. 
How does a subject currently quit in before completing all the available tasks? The experiment complete page seems to only allow either redoing or moving forward? Do they just close the window? Where is this explained?

When a subject stops before completing all the available task what is the status of the HIT on their end (since they have a dashboard of HITs they accept) and what is the status of the HIT on our end (is it submitted - it probably shouldn't be. Ideally it should be in progress but MTurk doesn't have that functionality to my knowledge)? How does this affect the available HITs?

**Comment by vsoch** [comment] 2016-03-13 08:33
I reviewed the changes that I made in the link that I posted on slack:

[https://github.com/expfactory/expfactory-docker/pull/65](https://github.com/expfactory/expfactory-docker/pull/65)

>> Right now subjects are asked to come back by storing a URL and coming back to it outside of MTurk (which I think could be problematic - what if they forget, loose etc.)

They can still come back to the page via amazon portal, they will just have to click through the consent again (and be taken to another random uncompleted experiment via the same URL). This isn't such bad behavior - my suggestion was to tell the users to keep track of the "accept" URL if they don't want to go through instructions again.

>> How does a subject currently quit in before completing all the available tasks? 

From my short use case, my understanding is that they can click "Return HIT" at any time, and it's returned.

>> The experiment complete page seems to only allow either redoing or moving forward? Do they just close the window? Where is this explained?

Anything / everything must be explained in the instructions, which is a text field input by the user when you create the battery:

![image](https://cloud.githubusercontent.com/assets/814322/13727707/54623f50-e8b2-11e5-8121-60b4bf3b42b7.png)

Different battery admins would have different desires for ad, instructions, consent, so we must allow the user to input these details and not "hard code" anything into the interface.

>> The experiment complete page seems to only allow either redoing or moving forward? Do they just close the window? Where is this explained?

If the user does not accept at the consent, this triggers a /finish page which automatically ends their participation. We could also provide this as a button at the end of an experiment, but my suggestion is not to do this, as it could be accidentally clicked, or inadvertently encourage a user who might be running out of steam to end a battery early when he/she might not have given the button wasn't there. I see no harm in not having the button, given that the user can just stop at any point that he / she wants.

>> When a subject stops before completing all the available task what is the status of the HIT on their end (since they have a dashboard of HITs they accept) and what is the status of the HIT on our end (is it submitted - it probably shouldn't be. 

It's only submitted if the user Returns, or if the amount of time passes that the battery endures (also specified at its creation) passes and the user has not returned.

>> Ideally it should be in progress but MTurk doesn't have that functionality to my knowledge)? How does this affect the available HITs?

I don't quite understand this question - I think it would be best if you created a Turker account, and tested some of these questions to get confirmation for yourself, and this would help us all work together to test. I will create you a superuser account on expfactory.org and email the credentials.

**Comment by bissettp** [comment] 2016-03-13 14:52
I have also been unable to follow the discussion completely. Could you also
create me a superuser account to test?

Best,

Patrick

On Sun, Mar 13, 2016 at 12:33 AM, Vanessa Sochat <notifications@github.com>
wrote:

> I reviewed the changes that I made in the link that I posted on slack:
>
> #65 <https://github.com/expfactory/expfactory-docker/pull/65>
>
> Right now subjects are asked to come back by storing a URL and coming back
> to it outside of MTurk (which I think could be problematic - what if they
> forget, loose etc.)
>
> They can still come back to the page via amazon portal, they will just
> have to click through the consent again (and be taken to another random
> uncompleted experiment via the same URL). This isn't such bad behavior - my
> suggestion was to tell the users to keep track of the "accept" URL if they
> don't want to go through instructions again.
>
> How does a subject currently quit in before completing all the available
> tasks?
>
> From my short use case, my understanding is that they can click "Return
> HIT" at any time, and it's returned.
>
> The experiment complete page seems to only allow either redoing or moving
> forward? Do they just close the window? Where is this explained?
>
> Anything / everything must be explained in the instructions, which is a
> text field input by the user when you create the battery:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/814322/13727707/54623f50-e8b2-11e5-8121-60b4bf3b42b7.png>
>
> Different battery admins would have different desires for ad,
> instructions, consent, so we must allow the user to input these details and
> not "hard code" anything into the interface.
>
> The experiment complete page seems to only allow either redoing or moving
> forward? Do they just close the window? Where is this explained?
>
> If the user does not accept at the consent, this triggers a /finish page
> which automatically ends their participation. We could also provide this as
> a button at the end of an experiment, but my suggestion is not to do this,
> as it could be accidentally clicked, or inadvertently encourage a user who
> might be running out of steam to end a battery early when he/she might not
> have given the button wasn't there. I see no harm in not having the button,
> given that the user can just stop at any point that he / she wants.
>
> When a subject stops before completing all the available task what is the
> status of the HIT on their end (since they have a dashboard of HITs they
> accept) and what is the status of the HIT on our end (is it submitted - it
> probably shouldn't be.
>
> It's only submitted if the user Returns, or if the amount of time passes
> that the battery endures (also specified at its creation) passes and the
> user has not returned.
>
> Ideally it should be in progress but MTurk doesn't have that functionality
> to my knowledge)? How does this affect the available HITs?
>
> I don't quite understand this question - I think it would be best if you
> created a Turker account, and tested some of these questions to get
> confirmation for yourself, and this would help us all work together to
> test. I will create you a superuser account on expfactory.org and email
> the credentials.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/expfactory/expfactory-docker/issues/66#issuecomment-195914424>
> .
>



-- 
Patrick G. Bissett
Postdoctoral Fellow
Stanford University

**Comment by IanEisenberg** [comment] 2016-03-13 23:49
Ok, a few things about terminology that perhaps I am confused about but I want to make sure we are all on the same page.

"Returning" a HIT, an option a worker always has is "I realize I don't want to complete this - let someone else try it". If they return a HIT, they are not credited for the HIT (not paid). I'm not sure if we can even bonus them if they do this (but I may be wrong about this point).

"quitting" our experiment is not the same. To "quit" our experiment and still get paid they should just not come back. If they do so they will automatically not get approved (right @vsoch?) in that they will have "failed" many tasks that they didn't completed. Because of this, they will not be "approved" (so they won't get the automatic $60 payment), but will then have a bonus payment calculated based on the work done. I'm not sure if that's automatically calculated now (it requires that our experiment times are on point to calculate "hours" worked), but for the initial pilot we can just manually take care of that for people who drop out.

One thing I am not clear about is what happens if we "blacklist" them? Does that just prevent new experiments from showing up or are they "rejected" somehow by us? If they are, how do we pay them for work done? Can we bonus them?

**Comment by vsoch** [comment] 2016-03-14 00:07
I'm not familiar with the subtleties of the different options for Mechanical Turk that are available to the Turker from Amazon. Think of it this way. We use Boto to control the same functions that are provided by Amazon, and we have a very minimal design that will simply run a function to assign credit when an experiment finishes, or when the time runs out. The function also parses the bonus conditions provided by the researcher, and will add bonus if the data meet those conditions. That's it.  This means that:

- If a worker returns a HIT and they aren't able to be paid as determined by Amazon, it's not going to work when we try to do the same thing with Boto. I'm not sure about bonuses, but since allocating any kind of reward required approving the HIT, I'm guessing no.
- Quitting just means not going back to the browser page, and not necessarily returning the HIT. If someone quits, the time will run out, and the function will run to allocate credit. The criteria for rejection are completely determined by what the researcher specifies in the config.json. I originally implemented it so that if any rejection criteria were triggered, the HIT would be rejected. We had a meeting @IanEisenberg where you said something like "we are nicer in research, just probably don't want to reject anyone for now" and so I [commented that code out](https://github.com/expfactory/expfactory-docker/blob/master/expdj/apps/turk/tasks.py#L79). If your feelings are different now, please specify the procedure you would like to do.
- We do not have any kind of counter for "how many failed tasks" are allowed.

I'm not familiar with blacklist. I think it might be best if you want to read and better understand these different conditions, and provide a clear outline of the procedure you would like implemented in our application, to supplement whatever is provided by Amazon. Also remember that we have the expfactory.org to create and generate the HITS, but we also have the entire Amazon interface available to us.

**Comment by vsoch** [comment] 2016-03-16 20:00
There is no clear direction for this issue, and I think it has been worked out (and mostly resolved) in other issues. Closing.

**Closed by vsoch** 2016-03-16 20:00 UTC
